name: MCT-PreviewBuild

on:
  push:
    branches: [ "Preview" ]
  pull_request:
    branches: [ "Preview" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CMake build
      run: |
        cd ${{ github.workspace }}
        ls
        mkdir build
        cd build
        cmake --version
        cmake ../
      shell: sh
    - name: Make build
      run: |
        cd ${{ github.workspace }}
        ls
        cd build
        make
      shell: sh
    - name: Upload exec file
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MCT-Pre
        path: build/MCT

