name: MCT-PreviewBuild

on:
  push:
    branches: [ "Preview" ]
  pull_request:
    branches: [ "Preview" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build-linux
      run: make
      working-directory: src/
    - name: Build Preview MCT-Linux
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MCT-Pre
        path: src/MCT

