name: Stable-Build

on:
  push:
    branches: [ "Stable" ]
  pull_request:
    branches: [ "Stable" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CMake build
      run: |
        cd ${{ github.workspace }}
        ls
        mkdir build
        cd build
        cmake --version
        cmake ../
        echo "Done!"
      shell: sh
    - name: Make build
      run: |
        cd ${{ github.workspace }}
        ls
        cd build
        make
        echo "Done!"
      shell: sh
    - name: Upload exec file
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MCT-Stable
        path: build/MCT

