name: MCT-StableBuild

on:
  push:
    branches: [ "Stable" ]
  pull_request:
    branches: [ "Stable" ]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build-linux
      run: make
      working-directory: src
    - name: Build MCT-Linux
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MCT-Linux
        path: src/MCT-Linux
 
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: build-windows
      run: g++ MCT-Windows.cpp -o MCT-Windows.exe
      working-directory: src
    - name: Build MCT-Windows
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MCT-Windows
        path: src/MCT-Windows
